main: main.c
	gcc main.c -o main

clean:
	rm -f main out

test1:
	./main -input trace/trace1.txt -output out1

test2:
	./main -input trace/trace2.txt -output out2

test3:
	./main -input trace/trace3.txt -output out3
